language: java
jdk: openjdk8
sudo: false
notifications:
  slack:
    secure: f2lylRvGcAr6C+boZ/weJ6Hvb2FcK8oE2SL9AuXaoh9pTHM6vg22IUMswroE4dj5njYoS0+N64yjWd2r+D5sE+qmcGc/3Yb6XcGxP204x06nERDhv/kVbgrwgUlLxinWJLtoAvXwHOy1zolyGa7WgmYZ4znN1tAoD1OUL51PTsv/7IUzm0SXqsP3+BlFt83snEyI/WCONgS/gxVwnh0ciUVg228pj93LREdk/iO1Zn8XqhxGGXtqVnPUJ0UidB6IzMVkpaiVPO7hCNnwIhmS7ZDNXtUFSD0JzKYrpSVhga/cXJ4NN6MtJ9g5fwERVHtQXfKV+O2nqvVO9uGOIq1s1kF4LeVT555Z+Diwpn7G4B8WqhFeW3veGU/KqzXT09rQnxmLONKlEK2zr8Bx4C8ZOx9TLW5ELO+vXJliPM7I/umaAaQWaFoCNGnsdFY/aXcp3/ASe8ob5VtO8EV29hh1daab0k9NxdHk6XwqZOT7ex4agEs0A9smGyvrjkNQ5eOJDy6U35dBHi9ilNv62c8QDlG6hgCZwIBfsucwvY31HcJvmElhzBdei2KKIaljl5UQy3RRT1C99dI+88PKOoURMI+whmQxa+0Cuek46J4opGFeSLlreP7GVtYLFxnlaA97RZYswIthlaxBMiV8zdG2k6Q22hkb2GIX1GpE5m5TyU4=
deploy:
  provider: releases
  api_key:
    secure: p9Dw6VFBwZqzNDVvoQsX2KrS10DvSMUe93hfU2eoL0pDIqyCm8wm3P/JIkK3phijOANAn2mRXvXmWaAn1wtq00iO2J7Lam/E8mXzlsLRCwKSzipjTQbgCP9/OqdssnOh/F9Ppa4VTqJJcR+WZZ/Drz9Yg2+P4TytA64nbuCnCh748RFJhfHKO0Z/X+GmOhAVjDkQMshIRXUInXTjVMjs1rrtWFCHR6z3TUO3z61flrFOD67kOzJsil0UI2QjPBTNebN+HLxMxm9OzE5KZ2ll8eelk1L9Xen0V1ux7oJRjBYlc0iPg4KzpMVASf90RlXWmDqg3k24wtIUmbpKwEY3pYKRdg09SbFkRThDHOuTCcUmPBNsa2VOgfL8AvjbRRzMl7oLOD9VFSVGck/IcvqgclJ1JIpM4R/NuhDxbkecv8+8Ee5dWyPcsnGzSDSFVeGen1f9lIVoW29vsQdSCcFzmL/9+eueV+CUUKmYQtVvFmrhEF94sa24U3xJCOfLTPJJSulX7W+2/ykV653wkdfw0bkwDOfBS0bjdkg8CJqZxwYEa1nVKJax9luKGEbtYxYjrwwGaV8s4yHJN/33NeG/eLaI6q79BRcPRPki1MmUe1y1pKS319tPyzQrCC2Wy4F3pd2XHHsQ/iS8DXpYTROIOdhM/TQ/aiSkoSOMW2iIuV8=
  file: build/libs/*
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xld-tableau-plugin
